"""Sync anouncement

Revision ID: 4305f5de0544
Revises: 0a48880e9c72
Create Date: 2024-11-06 18:12:21.880292

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4305f5de0544'
down_revision: Union[str, None] = '0a48880e9c72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('posts')
    op.drop_table('products')
    
    op.add_column('announcement', sa.Column('admin_id', sa.Integer(), nullable=True, server_default='1'))
    op.create_foreign_key(None, 'announcement', 'admin', ['admin_id'], ['id'], ondelete='CASCADE')
    
    # Make `admin_id` non-nullable now that it has a default value
    op.alter_column('announcement', 'admin_id', nullable=False, server_default=None)


    op.create_foreign_key(None, 'announcement', 'admin', ['admin_id'], ['id'], ondelete='CASCADE')
    op.drop_column('announcement', 'user_id')
    op.add_column('post', sa.Column('club_id', sa.Integer(), nullable=False))
    op.drop_constraint('post_user_fkey', 'post', type_='foreignkey')
    op.create_foreign_key(None, 'post', 'club', ['club_id'], ['id'], ondelete='CASCADE')
    op.drop_column('post', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'post', type_='foreignkey')
    op.create_foreign_key('post_user_fkey', 'post', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('post', 'club_id')
    op.add_column('announcement', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'announcement', type_='foreignkey')
    op.drop_column('announcement', 'admin_id')
    op.create_table('products',
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('price', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('is_sale', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('inventory', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='products_pkey')
    )
    op.create_table('posts',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('content', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('published', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='posts_pkey')
    )
    # ### end Alembic commands ###
